version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongo:27017/webapp
      - JWT_SECRET=your_jwt_secret_here
      - FIREBASE_PROJECT_ID=your_firebase_project_id
    depends_on:
      - mongo
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: npm run dev

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_BASE_URL=http://localhost:5000/api
      - REACT_APP_FIREBASE_API_KEY=your_firebase_api_key
      - REACT_APP_FIREBASE_AUTH_DOMAIN=your_project.firebaseapp.com
      - REACT_APP_FIREBASE_PROJECT_ID=your_firebase_project_id
      - REACT_APP_FIREBASE_STORAGE_BUCKET=your_project.appspot.com
      - REACT_APP_FIREBASE_MESSAGING_SENDER_ID=your_sender_id
      - REACT_APP_FIREBASE_APP_ID=your_app_id
    depends_on:
      - backend

  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password

volumes:
  mongo_data:
